#          YAML Reference Guide: 
# Environmental Variables Guide: https://docs.travis-ci.com/user/environment-variables/
#                YAML Validator: travis lint ./.travis.yml

# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.


#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
#branches:
  # whitelist
  #only:
    #- master

  # blacklist
  #except:

#jobs:
  #include:
    #- stage:

language: generic
#dotnet:
#gemfile:
#mono:
#php:
#python:
#rvm:

#git:
  #depth:
  #submodules:

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
os:
  - linux
  - osx

sudo: required

dist: trusty

osx_image: xcode9.1

# environment variables
#env:
  #global:
  #matrix:

matrix:
  #fast_finish: true
  #allow_failures:
  include:
    - os: linux
    - os: osx
  #exclude:

# build cache to preserve files/folders between builds
#cache:

# enable service required for build/tests
#services:
  #- cassandra           # start Apache Cassandra
  #- couchdb             # start CouchDB
  #- elasticsearch       # start ElasticSearch
  #- memcached           # start Memcached
  #- mongodb             # start MongoDB
  #- mysql               # start MySQL
  #- neo4j               # start Neo4j Community Edition
  #- postgresql          # start PostgreSQL
  #- rabbitmq            # start RabbitMQ
  #- redis-server        # start Redis
  #- riak                # start Riak
 
#addons:
  #apt:
    #sources:
      #- sourceline: https://packages.microsoft.com/config/ubuntu/14.04/prod.list
        #key_url: https://packages.microsoft.com/keys/microsoft.asc
    #packages:
      #- powershell
  #artifacts:
    #paths:
      #- ./tests/results/Travis*.xml
  #chrome:
  #firefox:
  #hosts:
  #mariadb:
  #rethinkdb:
  #sauce_connect:
    #username:
    #access_key:
  #ssh_known_hosts:

#before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      #brew tap caskroom/cask
      #brew cask install powershell
    #fi

install:
  - chmod +x ./build/travis/install-dependencies.sh
  - sh ./build/travis/install-dependencies.sh
  - powershell -File ./build/shared/install-dependencies.ps1
  # spellcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      nvm install 6.4.0 &&
      npm install -g markdown-spellcheck@0.11.0;
    fi
  - ulimit -n 4096


#---------------------------------#
#       tests configuration       #
#---------------------------------#

#before_script:

script:
  - powershell -File ./build/shared/build.ps1
  - powershell -File ./tests/start-tests.ps1
  # spellcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mdspell '**/*.md' '!powershell/**/*.md' --ignore-numbers --ignore-acronyms --report;
    fi

#before_cache:

# on successful build
#after_success:

# on build failure
#after_failure:


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# scripts to run before deployment
#before_deploy:

#deploy:
  #skip_cleanup:

# scripts to run after deployment
#after_deploy:

# after build failure or success
#after_script:


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  email: false
  slack:
    secure: TpslQKjfhzkDLlAxaxLyV0LEi2bZe+HcJU+mxJuxlX6zfbG8KalJz5IcOv8Y2/YNmj5+Svtu1/w09DScAkWKsXdh9SCBgYRKzd1tfgqOGF71KA/IryIBYNwYwFSNgGtqoYdBc/mnp8n8ayXpLvF+8HpphDaXXZLstcd35J6lwG7MSQVx8R2oWiMuhZiwGJBzGl+XB5dT4qCzpIADwpBU3N8Z5GfmMFWbjsRRJCRFcXedESuIAqPmUzCxS9hPYLna1YHe6aAMG18jLsFrF55sTDJW8YK5X92/DkVI/REkpvpqD65GEhBcpoZ6WVfWkpHC1tbLHO1r7wbFuaQFx+Vlt6dfpA+Hnf4cpmXKE8ppjaKCzBj7BGJJNWdSjd/w+lsiUKnGTALd/uTonK6l+fevK5IlROgcU3Oq++I6t8Wzs0nkNQyhM9qE+GcyfzfwyKwRrdB9zROXNrLa1UGedsC/tQhUGRwKN/GxGUDIJ0qbiRxFEmj52t/spzadb5p0mFmFKwPZuBheMk2slwUNM+Zq/q1NWYVRPH+NHr57PFdXU1pa6OmPVP7/qb4PuKuOXzWag5hMhvo3NoHcztRVcVmihqyGYM3aaGYfmmtqK8WFalL3ccRYcjY9qudvDZj9LB6YFQt0dA0TlPGDPbPP3wuAHMW3VZz7cn6hDe5USzDk+pk=
