#          YAML Reference Guide: https://www.appveyor.com/docs/appveyor-yml/
# Environmental Variables Guide: https://www.appveyor.com/docs/environment-variables/
#                YAML Validator: https://ci.appveyor.com/tools/validate-yaml

# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.


#---------------------------------#
#      general configuration      #
#---------------------------------#

language: cpp
#rvm:

git:
  depth: 1000


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
os:
  - linux
  - osx

sudo: required

dist: trusty

osx_image: xcode9.1

# environment variables
#env:

#matrix:

# build cache to preserve files/folders between builds
#cache:

# enable service required for build/tests
#services:

addons:
  apt:
    sources:

before_install:


install:
  - chmod +x ./build/travis/install-dependencies.sh
  - ./build/travis/install-dependencies.sh
  - powershell -File ./build/shared/install-dependencies.ps1
  # spellcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      nvm install 6.4.0 &&
      npm install -g markdown-spellcheck@0.11.0;
    fi
  - ulimit -n 4096

script:
  - powershell -File ./build/shared/build.ps1
  # spellcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mdspell '**/*.md' '!powershell/**/*.md' --ignore-numbers --ignore-acronyms --report;
    fi

notifications:
  slack:
    secure: TpslQKjfhzkDLlAxaxLyV0LEi2bZe+HcJU+mxJuxlX6zfbG8KalJz5IcOv8Y2/YNmj5+Svtu1/w09DScAkWKsXdh9SCBgYRKzd1tfgqOGF71KA/IryIBYNwYwFSNgGtqoYdBc/mnp8n8ayXpLvF+8HpphDaXXZLstcd35J6lwG7MSQVx8R2oWiMuhZiwGJBzGl+XB5dT4qCzpIADwpBU3N8Z5GfmMFWbjsRRJCRFcXedESuIAqPmUzCxS9hPYLna1YHe6aAMG18jLsFrF55sTDJW8YK5X92/DkVI/REkpvpqD65GEhBcpoZ6WVfWkpHC1tbLHO1r7wbFuaQFx+Vlt6dfpA+Hnf4cpmXKE8ppjaKCzBj7BGJJNWdSjd/w+lsiUKnGTALd/uTonK6l+fevK5IlROgcU3Oq++I6t8Wzs0nkNQyhM9qE+GcyfzfwyKwRrdB9zROXNrLa1UGedsC/tQhUGRwKN/GxGUDIJ0qbiRxFEmj52t/spzadb5p0mFmFKwPZuBheMk2slwUNM+Zq/q1NWYVRPH+NHr57PFdXU1pa6OmPVP7/qb4PuKuOXzWag5hMhvo3NoHcztRVcVmihqyGYM3aaGYfmmtqK8WFalL3ccRYcjY9qudvDZj9LB6YFQt0dA0TlPGDPbPP3wuAHMW3VZz7cn6hDe5USzDk+pk=
