language: cpp

git:
  depth: 1000

os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode9.1

install:
  - pushd tests
  - chmod +x ./travis-install-dependencies.sh
  - ./travis-install-dependencies.sh
  - popd
  # spellcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      nvm install 6.4.0 &&
      npm install -g markdown-spellcheck@0.11.0;
    fi
  - ulimit -n 4096

script:
  - powershell -File ./tests/travis-build.ps1
  # spellcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mdspell '**/*.md' '!powershell/**/*.md' --ignore-numbers --ignore-acronyms --report;
    fi