#          YAML Reference Guide: 
# Environmental Variables Guide: https://docs.travis-ci.com/user/environment-variables/
#                YAML Validator: travis lint ./.travis.yml

# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.


#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
#branches:
  # whitelist
  #only:
    #- master

  # blacklist
  #except:

#jobs:
  #include:
    #- stage:

language: generic
#dotnet:
#gemfile:
#mono:
#php:
#python:
#rvm:

#git:
  #depth:
  #submodules:

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
#os:
  #- linux
  #- osx

#sudo: required

#dist: trusty

#osx_image: xcode9.1

# environment variables
env:
  global:
    secure: "Q3vmE6RYSo8zpmzzFsZoYO7Q9mQvX32dMyLiSEOXEoDq41vc8OJyctpOTtoQmme9tAgzZrv9cdCbhfOsLfVtILbTrHWj8ktvTv7dQg29Qa1tH9IwPHL300RSPB1vBijtBTpuJ77NFjJUmaBSkB0Ixz0/2/nO7qhyLOUcxCAsNk53oHJzfxSOPo0WjiMamYDdcVVdxluogEu2Zgjm4V8J0KxSyFPKqeALvNnKRUWTe4m/ouetr9M5+19Z2uNpUDh90Gl9YQVXT4XZldt6tgwrDajz6uo6TM/3E4IKvNiu+NvvI9zF/tIwWL2R2wm/kZczN95m9cTVyPsbOzJTutcxP3xxZNe+O4gK0ToQVCUL8bjcIDaf66XQ4zS9fo77UYfNAl/JFFOtq4EfMwBuouBxVyAqriFnInbqADSycVEnYcdx0JCRFAQLpemyF+29cSSpDSySYpf1nP3EjOPBfWLCfMe0U0pSdag4T0nFxLL70Abd/AOfrXXTnLdRci4I2QMaHdKX1CEnx7sCBhtAwmKnxqhlR8uB2APb8gl+wbzBwl7bv6rRSplVApjcBQbydHJbk+QkFQBuPOI5BNMZYsqjhlJxAL+XOZfEn7NUtBjCyl4cb6SesooCtqHvhgfqeFYdiRmv0pYd9rnUfeZxr7dpI1CPhLLngsl1l1ey13DX164="
  #matrix:

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.1
  fast_finish: true
  #allow_failures:
  #exclude:

# build cache to preserve files/folders between builds
#cache:

# enable service required for build/tests
#services:
  #- cassandra           # start Apache Cassandra
  #- couchdb             # start CouchDB
  #- elasticsearch       # start ElasticSearch
  #- memcached           # start Memcached
  #- mongodb             # start MongoDB
  #- mysql               # start MySQL
  #- neo4j               # start Neo4j Community Edition
  #- postgresql          # start PostgreSQL
  #- rabbitmq            # start RabbitMQ
  #- redis-server        # start Redis
  #- riak                # start Riak
 
#addons:
  #apt:
    #sources:
      #- sourceline: "deb https://packages.microsoft.com/config/ubuntu/14.04/prod.list main"
        #key_url: "https://packages.microsoft.com/keys/microsoft.asc"
    #packages:
      #- powershell
  #artifacts:
    #paths:
      #- ./tests/results/Travis*.xml
  #chrome:
  #firefox:
  #hosts:
  #mariadb:
  #rethinkdb:
  #sauce_connect:
    #username:
    #access_key:
  #ssh_known_hosts:

#before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      #brew update > /dev/null;
      #brew install curl --with-openssl;
      #brew tap caskroom/cask;
      #brew cask install powershell;
    #fi

install:
  - sudo chmod +x ./build/travis/install-dependencies.sh
  - ./build/travis/install-dependencies.sh
  - sudo pwsh -file ./build/shared/install-dependencies.ps1
  # spellcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      nvm install 6.4.0;
      npm install -g markdown-spellcheck@0.11.0;
    fi


#---------------------------------#
#       tests configuration       #
#---------------------------------#

#before_script:

script:
  - pwsh -file ./build/shared/build.ps1
  - pwsh -file ./tests/start-tests.ps1
  # spellcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mdspell '**/*.md' --ignore-numbers --ignore-acronyms --report;
    fi

#before_cache:

# on successful build
#after_success:

# on build failure
#after_failure:


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# scripts to run before deployment
#before_deploy:

#deploy:
  #skip_cleanup:

# scripts to run after deployment
#after_deploy:

# after build failure or success
#after_script:


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  email: false
  slack:
    secure: TpslQKjfhzkDLlAxaxLyV0LEi2bZe+HcJU+mxJuxlX6zfbG8KalJz5IcOv8Y2/YNmj5+Svtu1/w09DScAkWKsXdh9SCBgYRKzd1tfgqOGF71KA/IryIBYNwYwFSNgGtqoYdBc/mnp8n8ayXpLvF+8HpphDaXXZLstcd35J6lwG7MSQVx8R2oWiMuhZiwGJBzGl+XB5dT4qCzpIADwpBU3N8Z5GfmMFWbjsRRJCRFcXedESuIAqPmUzCxS9hPYLna1YHe6aAMG18jLsFrF55sTDJW8YK5X92/DkVI/REkpvpqD65GEhBcpoZ6WVfWkpHC1tbLHO1r7wbFuaQFx+Vlt6dfpA+Hnf4cpmXKE8ppjaKCzBj7BGJJNWdSjd/w+lsiUKnGTALd/uTonK6l+fevK5IlROgcU3Oq++I6t8Wzs0nkNQyhM9qE+GcyfzfwyKwRrdB9zROXNrLa1UGedsC/tQhUGRwKN/GxGUDIJ0qbiRxFEmj52t/spzadb5p0mFmFKwPZuBheMk2slwUNM+Zq/q1NWYVRPH+NHr57PFdXU1pa6OmPVP7/qb4PuKuOXzWag5hMhvo3NoHcztRVcVmihqyGYM3aaGYfmmtqK8WFalL3ccRYcjY9qudvDZj9LB6YFQt0dA0TlPGDPbPP3wuAHMW3VZz7cn6hDe5USzDk+pk=
