#          YAML Reference Guide: https://www.appveyor.com/docs/appveyor-yml/
# Environmental Variables Guide: https://www.appveyor.com/docs/environment-variables/
#                YAML Validator: https://ci.appveyor.com/tools/validate-yaml

# Disable automatic builds
# Without this, the following error shows up:
# "Specify a project or solution file. The directory does not contain a project or solution file."
build: off

# Version number
version: 1.0.0.{build}

# Ignore testing a commit if only the README.md file changed
skip_commits:
  files:
    - README.md
  message: /Merge branch .+ of .+ArmorPowerShell/

# There's no need to alter the build number for a Pull Request (PR) since they don't modify anything
pull_requests:
  do_not_increment_build_number: true

# PowerShell Gallery API key for publishing an update to the module
# The "secure:" value is the Appveyor encryption of the key
environment:
  EmailAddress:
    secure: 43DvfWEGMogavR46PXxh30oNdHE9mpp1Y/awYFP7kA4=
  GitHubKey:
    secure: C73uALUvX96LkyNxMJ2FtGMPHBANvjpviy9EFg33uYZowJEdS4DvsXS12fzT17BY
  NuGetApiKey:
    secure: u2jbw68/5JWUmA5z8fBok8TNO0BAJ41CSNGUJeVAtrIgDJ7p7TqW6dTbFmytP9UG

# Install NuGet to interact with the PowerShell Gallery
install:
- ps: |
    Install-PackageProvider -Name NuGet -Force | Out-Null
    Install-Module -Name Pester -Force
    Install-Module -Name posh-git -Force

# Invoke Pester to run all of the unit tests, then save the results into XML in order to populate the AppVeyor tests section
# If any of the tests fail, consider the pipeline failed
test_script:
  - ps: $testsResultsFilePath = '.\tests\results\AppVeyorTestsResults.xml'
  - ps: $testsResults = Invoke-Pester -Path ".\tests" -OutputFormat NUnitXml -OutputFile $testsResultsFilePath -PassThru
  - ps: ( New-Object -TypeName 'System.Net.WebClient' ).UploadFile( ( 'https://ci.appveyor.com/api/testresults/nunit/{0}' -f $env:APPVEYOR_JOB_ID ), ( Resolve-Path -Path $testsResultsFilePath ) )
  - ps: If ( $testsResults.FailedCount -gt 0 ) { Throw ( '{0} tests failed.' -f $testsResults.FailedCount ) }
  - git config --global credential.helper store
  - ps: Add-Content -Path ( '{0}\.git-credentials' -f $env:USERPROFILE ) -Value ( "https://{0}:x-oauth-basic@github.com`n" -f $env:GitHubKey )
  - git config --global user.email $env:EmailAddress
  - git config --global user.name 'Troy Lindsay'
  - git config --global core.autocrlf true
  - ps: . .\tests\appveyor-build.ps1

# Files generated during the build process that should be retained
artifacts:
  path: tests\results\*.xml

# Post a status update in Slack
# The "secure:" value is the Appveyor encryption of my Slack API token
notifications:
  - provider: Slack
    incoming_webhook:
      secure: Nd9G51DE8YpoOOF7ld2ZblBBzCcbkBxchFpE7Opc+RXJ8IEqBGplzeahMISj23z7bggF+bC2C6DoNpCTQE3DipzRd3YlFuDO0qqAGRdt8gw=
    channel: '#develop'
