#          YAML Reference Guide: https://www.appveyor.com/docs/appveyor-yml/
# Environmental Variables Guide: https://www.appveyor.com/docs/environment-variables/
#                YAML Validator: https://ci.appveyor.com/tools/validate-yaml

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

version: 1.0.{build}

branches:
  except:
  - gh-pages

skip_tags: true

pull_requests:
  do_not_increment_build_number: true

max_jobs: 5

image:
- Visual Studio 2015
- Visual Studio 2017
- Ubuntu

for:
- matrix:
    only:
    - PowerShell: 6
      image: Visual Studio 2017
  build_script:
  - pwsh: ./build/build.ps1 -DeploymentMode
- matrix:
    only:
    - PowerShell: 5
  build_script:
  - ps: ./build/build.ps1
- matrix:
    only:
    - PowerShell: 6
  build_script:
  - pwsh: ./build/build.ps1

matrix:
  exclude:
  - PowerShell: 5
    image: Ubuntu

clone_depth: 50

environment:
  APPVEYOR_CACHE_SKIP_RESTORE: true
  APPVEYOR_CACHE_SKIP_SAVE: true
  EMAIL_ADDRESS:
    secure: 43DvfWEGMogavR46PXxh30oNdHE9mpp1Y/awYFP7kA4=
  GITHUB_API_KEY:
    secure: C73uALUvX96LkyNxMJ2FtGMPHBANvjpviy9EFg33uYZowJEdS4DvsXS12fzT17BY
  NUGET_API_KEY:
    secure: u2jbw68/5JWUmA5z8fBok8TNO0BAJ41CSNGUJeVAtrIgDJ7p7TqW6dTbFmytP9UG
  COVERALLS_API_KEY:
    secure: WWnf4Q5NJHBpILI4QpagjvIO4lKmqu3wa3u/vhDXRivO2Xsr4xt3XEsswAG0vryE
  matrix:
  - PowerShell: 5
  - PowerShell: 6

artifacts:
- path: ./BuildOutput/TestResults.xml
  name: Pester Test Results
  type: Auto
- path: ./BuildOutput/CodeCoverageResults.xml
  name: Pester Code Coverage Results
  type: Auto

notifications:
- provider: Email
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
- provider: GitHubPullRequest
  auth_token:
    secure: C73uALUvX96LkyNxMJ2FtGMPHBANvjpviy9EFg33uYZowJEdS4DvsXS12fzT17BY
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"
- provider: Webhook # Gitter
  url:
    secure: VMG8UrlePL6sWol/IyQFbaCGkOLY9jFz+3wRnBG+rf95z9hLULTCpi+lN4xhSxwi4PyVEtDfstxeUA4/3+aP+g==
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
