site_name: "The Armor Community PowerShell Module"
site_author: "Troy Lindsay"
repo_url: "https://github.com/tlindsay42/ArmorPowerShell/"
theme: "readthedocs"
copyright: "(c) 2017-2018 Troy Lindsay. All rights reserved."
pages:
  - Home: "index.md"
  - User Documentation:
    - Requirements: "User/Requirements.md"
    - Install: "User/Install.md"
    - Update: "User/Update.md"
    - Uninstall: "User/Uninstall.md"
    - Getting Started: "User/Getting_Started.md"
    - Project Architecture: "User/Project_Architecture.md"
    - Licensing: "User/Licensing.md"
    - FAQs: "User/FAQs.md"
  - Command Documentation:
    - Connect-Armor: "Public/Connect-Armor.md"
    - Disconnect-Armor: "Public/Disconnect-Armor.md"
    - Get-ArmorAccount: "Public/Get-ArmorAccount.md"
    - Get-ArmorAccountAddress: "Public/Get-ArmorAccountAddress.md"
    - Get-ArmorAccountContext: "Public/Get-ArmorAccountContext.md"
    - Get-ArmorCompleteDatacenter: "Public/Get-ArmorCompleteDatacenter.md"
    - Get-ArmorCompleteWorkload: "Public/Get-ArmorCompleteWorkload.md"
    - Get-ArmorCompleteWorkloadTier: "Public/Get-ArmorCompleteWorkloadTier.md"
    - Get-ArmorIdentity: "Public/Get-ArmorIdentity.md"
    - Get-ArmorUser: "Public/Get-ArmorUser.md"
    - Get-ArmorVM: "Public/Get-ArmorVM.md"
    - Invoke-ArmorWebRequest: "Public/Invoke-ArmorWebRequest.md"
    - Remove-ArmorCompleteWorkload: "Public/Remove-ArmorCompleteWorkload.md"
    - Rename-ArmorCompleteWorkload: "Public/Rename-ArmorCompleteWorkload.md"
    - Rename-ArmorCompleteVM: "Public/Rename-ArmorCompleteVM.md"
    - Reset-ArmorCompleteVM: "Public/Reset-ArmorCompleteVM.md"
    - Restart-ArmorCompleteVM: "Public/Restart-ArmorCompleteVM.md"
    - Set-ArmorAccountContext: "Public/Set-ArmorAccountContext.md"
    - Start-ArmorCompleteVM: "Public/Start-ArmorCompleteVM.md"
    - Stop-ArmorCompleteVM: "Public/Stop-ArmorCompleteVM.md"
  - Private Functions:
    - Format-ArmorApiRequestBody: "Private/Format-ArmorApiRequestBody.md"
    - Get-ArmorApiData: "Private/Get-ArmorApiData.md"
    - New-ArmorApiToken: "Private/New-ArmorApiToken.md"
    - New-ArmorApiUri: "Private/New-ArmorApiUri.md"
    - New-ArmorApiUriQuery: "Private/New-ArmorApiUriQuery.md"
    - Select-ArmorApiResult: "Private/Select-ArmorApiResult.md"
    - Submit-ArmorApiRequest: "Private/Submit-ArmorApiRequest.md"
    - Test-ArmorSession: "Private/Test-ArmorSession.md"
    - Update-ArmorApiToken: "Private/Update-ArmorApiToken.md"
