# https://www.mkdocs.org/user-guide/configuration/

site_name: "The Armor Community PowerShell Module"
site_url: "https://tlindsay42.github.io/ArmorPowerShell/"
repo_url: "https://github.com/tlindsay42/ArmorPowerShell/"
repo_name: "GitHub"
edit_uri: "blob/master/docs/"
site_description: "This is a community project that provides a powerful command-line interface for managing and monitoring your Armor Complete (secure public cloud) and Armor Anywhere (security as a service) environments & accounts via a PowerShell module with cmdlets that interact with the published RESTful APIs."
site_author: "Troy Lindsay"
copyright: "(c) 2017-2018 Troy Lindsay. All rights reserved."
google_analytics: ["UA-117909744-3", "ArmorPowerShell"]
remote_branch: "gh-pages"
pages:
  - Home: "index.md"
  - User Documentation:
    - Requirements: "user/Requirements.md"
    - Install: "user/Install.md"
    - Update: "user/Update.md"
    - Uninstall: "user/Uninstall.md"
    - Getting Started: "user/Getting_Started.md"
    - Project Architecture: "user/Project_Architecture.md"
    - Licensing: "user/Licensing.md"
    - Contributing: "user/Contributing.md"
    - Code of Conduct: "user/Code_of_Conduct.md"
    - FAQs: "user/FAQs.md"
  - Cmdlet Documentation:
    - Module Description: "public/Armor.md"
    - Connect-Armor: "public/Connect-Armor.md"
    - Disconnect-Armor: "public/Disconnect-Armor.md"
    - Get-ArmorAccount: "public/Get-ArmorAccount.md"
    - Get-ArmorAccountAddress: "public/Get-ArmorAccountAddress.md"
    - Get-ArmorAccountContext: "public/Get-ArmorAccountContext.md"
    - Get-ArmorCompleteDatacenter: "public/Get-ArmorCompleteDatacenter.md"
    - Get-ArmorCompleteWorkload: "public/Get-ArmorCompleteWorkload.md"
    - Get-ArmorCompleteWorkloadTier: "public/Get-ArmorCompleteWorkloadTier.md"
    - Get-ArmorIdentity: "public/Get-ArmorIdentity.md"
    - Get-ArmorUser: "public/Get-ArmorUser.md"
    - Get-ArmorVM: "public/Get-ArmorVM.md"
    - Invoke-ArmorWebRequest: "public/Invoke-ArmorWebRequest.md"
    - Remove-ArmorCompleteWorkload: "public/Remove-ArmorCompleteWorkload.md"
    - Rename-ArmorCompleteWorkload: "public/Rename-ArmorCompleteWorkload.md"
    - Rename-ArmorCompleteVM: "public/Rename-ArmorCompleteVM.md"
    - Reset-ArmorCompleteVM: "public/Reset-ArmorCompleteVM.md"
    - Restart-ArmorCompleteVM: "public/Restart-ArmorCompleteVM.md"
    - Set-ArmorAccountContext: "public/Set-ArmorAccountContext.md"
    - Start-ArmorCompleteVM: "public/Start-ArmorCompleteVM.md"
    - Stop-ArmorCompleteVM: "public/Stop-ArmorCompleteVM.md"
  - Private Functions:
    - Format-ArmorApiRequestBody: "private/Format-ArmorApiRequestBody.md"
    - Get-ArmorApiData: "private/Get-ArmorApiData.md"
    - New-ArmorApiToken: "private/New-ArmorApiToken.md"
    - New-ArmorApiUri: "private/New-ArmorApiUri.md"
    - New-ArmorApiUriQuery: "private/New-ArmorApiUriQuery.md"
    - Select-ArmorApiResult: "private/Select-ArmorApiResult.md"
    - Submit-ArmorApiRequest: "private/Submit-ArmorApiRequest.md"
    - Test-ArmorSession: "private/Test-ArmorSession.md"
    - Update-ArmorApiToken: "private/Update-ArmorApiToken.md"
theme: "readthedocs"
strict: true
markdown_extensions:
  - admonition
